- name: play1
  hosts: local
  connection: local
  vars:
   COURSE: "DevOps with AWS"
   DURATION: 120HRS 
   TRAINER: Siva
  tasks: 
  - name: printing variable1
    ansible.buildin.debug:
     msg: "Course is {{ COURSE }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"

  tasks: 
  - name: printing variable2
    vars: 
     COURSE: "Ansible"
     DURATION: 12HRS 
     TRAINER: Sai
    ansible.buildin.debug:
     msg: "Course is {{ COURSE }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"   

