- name: play1
  hosts: local
  connection: local
  vars: # play variables or global vars
   COURSE: "DevOps with AWS"
   DURATION: 120HRS 
   TRAINER: Siva
  tasks: 
  - name: printing variable1
    ansible.builtin.debug:
     msg: "Course is {{ COURSE }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"


  - name: printing variable2
    vars: # task vars
     COURSE: "Ansible"
     DURATION: 12HRS 
     TRAINER: Sai
    ansible.builtin.debug:
     msg: "Course is {{ COURSE }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"   

