- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: "Please enter course name"
    private: false
  - name: DURATION
    prompt: "Please enter duration"
    private: false
  - name: TRAINER
    prompt: "Please enter trainer name"  
    private: true #what we type cannot be shown there
  tasks: 
  - name:
    ansible.builtin.debug:
     msg: "Course is {{ COURSE}}, Duration is {{ DURATION }} and {{TRAINER}}"  
