- name: ranking variables
  hosts: local
  connection: local
  vars:
   COURSE: "DevOps Play"
  vars_prompt:
   name: prompting
   prompt: Enter course name
  vars_files:
   source-vars.yaml   
  tasks:
  - name: tasking
    vars:
     COURSE: "DevOps Task" 
    ansible.builtin.debug:
     msg: Course {{ COURSE }}

    