- name: loops playbook
  hosts: local
  connection: local
  vars:
   my_number: 12
  tasks: 
  - name: checking number
    ansible.builtin.debug:
     msg: "15 is greater than {{ my_number }}"
    when: 15 > my_number