- name: Mysql configuration
  hosts: localhost
  become: yes
  tasks:
  - name: Installing Mysql-Server
    ansible.builtin.package:
     name: mysql-server
     state: present

  - name: Enable and Start Mysql-Server
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes 

  - name: Install MySQL libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - PyMySQL

  - name: connect to mysql server
    community.mysql.mysql_info:
     login_user: root
     login_password: "ExpenseApp@1"
     login_host: localhost
    register: mysql_info 
    ignore_errors: true
    

