- name: Mysql configuration
  hosts: localhost
  become: yes
  tasks:
  - name: Installing Mysql-Server
    ansible.builtin.package:
     name: mysql-server
     state: present
  - name: Enable and Start Mysql-Server
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes 
  - name: Setting-up Root password
    mysql_user:
     login_host: localhost
     login_user: root
     login_password: ExpenseApp@1
     state: present

