- name: Mysql configuration
  hosts: 172.31.26.243
  become: yes
  tasks:
  - name: Installing Mysql-Server
    ansible.builtin.package:
     name: mysql-server
     state: present
  - name: Enable and Start Mysql-Server
    ansible.builtin.service:
     name: mysql-server
     state: start
     enable: yes
